box: node:8
build:
  steps:
    - script:
      name: install yarn
      code: |
        npm install -g yarn

    - script:
      name: set yarn cache
      code: |
        export YARN_CACHE=$WERCKER_CACHE_DIR/yarn

    - script:
      name: install dependencies
      code: |
        HOME=$YARN_CACHE yarn

    - script:
      name: build
      code: |
        npm run build

    - script:
      name: cleanup dev dependencies
      code: |
        HOME=$YARN_CACHE yarn --prod
deploy:
  box: andthensome/alpine-surge-bash
  steps:
    - alrayyes/surge-deploy:
        login: $SURGE_LOGIN
        directory: $SURGE_DIRECTORY
        token: $SURGE_TOKEN
        domain: $SURGE_DOMAIN
